app1/urls.py
from django.urls import path
from app1.views import *

app_name='something'

urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='nothing'

urlpatterns=[
    path('virat/',virat,name='virat'),
]

project18/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include ('app1.urls')),
    path('app2/', include ('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render ( request,'dhoni.html') 

app2/views.py
from django.shortcuts import render

# Create your views here.
def virat (request):
    return render (request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
     <center>
        <h1>This is roshan html page</h1>
        <h1> This is belongs to</h1>
        <a href="{% url 'nothing:virat' %}"> naviagte to virat HTML page</a>
     </center>
    
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            welcome to virat HTML page
        </h1>
        <h1> this is belongs to app2 </h1>
        <a href="{% url 'something:dhoni' %}"> GO to dhoni page</a>
    </center>
</body>
</html>